Uniq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UniqApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UniqApp/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('category', CategoryView.as_view(), name="category"),
    path('about', AboutView.as_view(), name="about"),
    path('contact', ContactView.as_view(), name="contact"),

    path('adminpage', AdminPageView.as_view(), name="adminpage"),

    path('image-upload-view', ImageUploadView.as_view(), name="imageuploadview"),
    path('image-delete-view', ImageDeleteView.as_view(), name="imagedeleteview"),
    path('image-delete-button/<int:pk>/', ImageDeleteButton.as_view(), name="imagedeletebutton"),

    path('category-adding-view', CategoryAddingView.as_view(), name="categoryaddingview"),
    path('category-delete-view', CategoryDeleteView.as_view(), name="categorydeleteview"),
    path('category-delete-button/<int:pk>/', CategoryDeleteButton.as_view(), name="categorydeletebutton"),
    
    # Authentication -------------------------------
    path('signup', views.SignupView, name="signup"),
    path('accounts/profile/', ProfileView.as_view(), name="accountsprofile"),
]

UniqApp/models.py
from django.db import models

class Category(models.Model):
    title  = models.CharField(max_length=99)

    def __str__(self):
        return self.title

    # def __itr__(self):
    #     return [field.value_to_string(self) for field in Householdmember._meta.fields]

    

class Image(models.Model):
    image = models.ImageField(upload_to='dynamic_img')
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    

UniqApp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomSignup(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name')


class PictureAddingForm(forms.ModelForm):
    category : forms.ChoiceField()
    
    class Meta:
        model = Image
        fields = ["title", "category", "image"]

        widgets = {
            "title" : forms.TextInput(attrs={
                "class":"form-control",
                "placeholder":"Title",
            }),
        }

class CategoryAddingForm(forms.ModelForm):
    category : forms.ChoiceField()
    
    class Meta:
        model = Category
        fields = ["title"]

        widgets = {
            "title" : forms.TextInput(attrs={
                "class":"form-control",
                "placeholder":"Title",
            }),
        }

UniqApp/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.views.generic import *
from .models import *
from .forms import *

class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["images"] = Image.objects.all()
        return context
    
    # def get(self, request, *args, **kwargs):
    #     image = Image.objects.get(pk=self.kwargs['image_id'])
    #     image_buffer = open(image.file.path, "rb").read()
    #     content_type = magic.from_buffer(image_buffer, mime=True)
    #     response = HttpResponse(image_buffer, content_type=content_type);
    #     response['Content-Disposition'] = 'attachment; filename="%s"' % os.path.basename(image.file.path)
    #     return response

class CategoryView(TemplateView):
    template_name = 'category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context
    
class AboutView(TemplateView):
    template_name = "about.html"

class ContactView(TemplateView):
    template_name = "contact.html"

@method_decorator(staff_member_required, name='dispatch')
class AdminPageView(CreateView):
    template_name = 'admin.html'
    form_class = PictureAddingForm
    success_url = '/'
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ImageUploadView(CreateView):
    template_name = 'image_upload.html'
    form_class = PictureAddingForm
    success_url = '/adminpage'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class CategoryAddingView(CreateView):
    template_name = 'category_adding.html'
    form_class = CategoryAddingForm
    success_url = '/adminpage'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ImageDeleteView(TemplateView):
    template_name = 'image_delete_view.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["images"] = Image.objects.all()
        return context

class ImageDeleteButton(DeleteView):
    template_name = "image_confirm_delete.html"
    model = Image
    success_url = '/adminpage'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["images"] = Image.objects.all()
        return context

class CategoryDeleteView(TemplateView):
    template_name = 'category_delete_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context

class CategoryDeleteButton(DeleteView):
    template_name = "category_condirm_delete.html"
    model = Category
    success_url = "/adminpage"

def SignupView(request):
    form = CustomSignup()
    if request.method == 'POST':
        form = CustomSignup(request.POST)
        if form.is_valid():
            form.save()
            print("User succesfully registered")
            return redirect('login')
    return render(request, "registration/signup.html", {'form':form})
    
class ProfileView(TemplateView):
    template_name = 'profile.html'





"""

class SigninView(FormView):
    template_name = 'registration/login.html'
    form_class = OwnUserLoginForm
    success_url = '/'

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and User.objects.filter(username=uname, password=pword): #and User.objects.filter(user=usr).exists()
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form":self.form_class, "error":"Invalid Credentials"})
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url



class LogoutView(View):
    def get(self,request):
        x = logout(request)
        return redirect('home')
    

"""

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}

    <div class="container-fluid mt-4">
        <div class="row mb-4">
            <h2 class="col-12 tm-text-primary">
                About Uniq Walls
            </h2>
        </div>
        <div class="row tm-mb-74 tm-row-1640">            
            <div class="col-lg-5 col-md-6 col-12 mb-3">
                <img src="{% static 'img/about.jpg' %}" alt="Image" class="img-fluid">
            </div>
            <div class="col-lg-7 col-md-6 col-12">
                <div class="tm-about-img-text">
                    <p class="mb-4">
                  You may support TemplateMo website by making <a href="https://paypal.me/templatemo" target="_parent" rel="sponsored">a small contribution</a> via PayPal. This will be helpful for us. We hope you like this Catalog-Z photo / video template for your website. We are making new templates regularly for you. Please come back and visit our <a rel="sponsored" href="https://templatemo.com" target="_parent">TemplateMo website</a> again. </p>
                    <p>
                        Credits go to Pexels and Unsplash for photos and video used in this template. Catalog-Z is free <a rel="sponsored" href="https://v5.getbootstrap.com/">Bootstrap 5</a> Alpha 2 HTML Template designed for video and photo websites.</p> 
                    <p>You are <b>allowed</b> to use this template for your commercial or non-commercial websites. You can integrate it with any kind of CMS website. You are <b>NOT allowed</b> to redistribute the downloadable template ZIP file on any template collection website. Please <a rel="nofollow" href="https://templatemo.com/contact" target="_parent">contact us</a> for more information. Thank you.</p>
                </div>                
            </div>
        </div>
        <div class="row tm-mb-50">
            <div class="col-md-6 col-12">
                <div class="tm-about-2-col">
                    <h2 class="tm-text-primary mb-4">
                        Left side of 2-Column content
                    </h2>
                    <p class="mb-4">
                        Pellentesque urna odio, scelerisque eu mauris vitae, vestibulum sodales neque. Ut augue justo, tincidunt nec aliquet ac, cursus vel augue. Suspendisse vel quam imperdiet, sodales tellus sed, ullamcorper lorem.
                    </p>
                    <p>
                        Suspendisse id consequat risus. Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Aenean porta eleifend venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                    </p>
                </div>                
            </div> 
            <div class="col-md-6 col-12">
                <div class="tm-about-2-col">
                    <h2 class="tm-text-primary mb-4">
                        Right-side Title goes here
                    </h2>
                    <p class="mb-4">
                        Pellentesque urna odio, scelerisque eu mauris vitae, vestibulum sodales neque. Ut augue justo, tincidunt nec aliquet ac, cursus vel augue. Suspendisse vel quam imperdiet, sodales tellus sed, ullamcorper lorem.
                    </p>
                    <p>
                        Suspendisse id consequat risus. Aliquam varius posuere nunc, nec imperdiet neque condimentum at. Aenean porta eleifend venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                    </p>
                </div>                
            </div>     
        </div> <!-- row -->
        <div class="row tm-mb-50">
            <div class="col-md-4 col-12">
                <div class="tm-about-3-col">
                    <div class="tm-about-icon-container mb-5">
                        <i class="fas fa-desktop fa-3x tm-text-primary"></i>
                    </div>                
                    <h2 class="tm-text-primary mb-4">Three-column title one</h2>
                    <p class="mb-4">Integer tristique arcu scelerisque mauris posuere convallis. Fusce egestas ipsum sapien, hendrerit ultricies nisi viverra eget. Vestibulum in tortor eget elit rutrum interdum. </p>
                    <p>Cras auctor velit urna, et feugiat ex tincidunt ut. Sed viverra, elit at pulvinar tristique, sem quam vehicula dolor, sed scelerisque augue mauris non dolor.</p>
                </div>                
            </div>
            <div class="col-md-4 col-12">
                <div class="tm-about-3-col">
                    <div class="tm-about-icon-container mb-5">
                        <i class="fas fa-mobile-alt fa-3x tm-text-primary"></i>
                    </div>                
                    <h2 class="tm-text-primary mb-4">Title two of three-column</h2>
                    <p class="tm-mb-50">Donec nec est tincidunt, rhoncus nulla sit amet, imperdiet augue. Phasellus sodales placerat ipsum ac auctor. Mauris molestie blandit turpis. Mauris ante tellus, feugiat nec metus non, bibendum semper velit.</p>                
                    <div class="text-center">
                        <a href="#" class="btn btn-primary">Read More</a>
                    </div>
                </div>                
            </div>
            <div class="col-md-4 col-12">
                <div class="tm-about-3-col">
                    <div class="tm-about-icon-container mb-5">
                        <i class="fas fa-photo-video fa-3x tm-text-primary"></i>
                    </div>                
                    <h2 class="tm-text-primary mb-4">Third Title goes here</h2>
                    <p class="mb-4">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec nec est tincidunt, rhoncus nulla sit amet, imperdiet augue. </p>
                    <p>Phasellus sodales placerat ipsum ac auctor. Mauris molestie blandit turpis. Mauris ante tellus, feugiat nec metus non, bibendum semper velit.</p>
                </div>                
            </div>
        </div>
    </div> <!-- container-fluid, tm-container-content -->

    <footer class="tm-bg-gray pt-5 pb-3 tm-text-gray tm-footer">
        <div class="container-fluid tm-container-small">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-12 px-5 mb-5">
                    <h3 class="tm-text-primary mb-4 tm-footer-title">About Catalog-Z</h3>
                    <p>Catalog-Z is free Bootstrap 5 Alpha 2 HTML Template for video and photo websites. You can freely use this TemplateMo layout for a front-end integration with any kind of CMS website.</p>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12 px-5 mb-5">
                    <h3 class="tm-text-primary mb-4 tm-footer-title">Our Links</h3>
                    <ul class="tm-footer-links pl-0">
                        <li><a href="#">Advertise</a></li>
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Our Company</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12 px-5 mb-5">
                    <ul class="tm-social-links d-flex justify-content-end pl-0 mb-5">
                        <li class="mb-2"><a href="https://facebook.com"><i class="fab fa-facebook"></i></a></li>
                        <li class="mb-2"><a href="https://twitter.com"><i class="fab fa-twitter"></i></a></li>
                        <li class="mb-2"><a href="https://instagram.com"><i class="fab fa-instagram"></i></a></li>
                        <li class="mb-2"><a href="https://pinterest.com"><i class="fab fa-pinterest"></i></a></li>
                    </ul>
                    <a href="#" class="tm-text-gray text-right d-block mb-2">Terms of Use</a>
                    <a href="#" class="tm-text-gray text-right d-block">Privacy Policy</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-7 col-12 px-5 mb-3">
                    Copyright 2020 Catalog-Z Company. All rights reserved.
                </div>
                <div class="col-lg-4 col-md-5 col-12 px-5 text-right">
                    Designed by <a href="https://templatemo.com" class="tm-text-gray" rel="sponsored" target="_parent">TemplateMo</a>
                </div>
            </div>
        </div>
    </footer>
{% endblock photos %}
   

templates/admin.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}

<p>ss</p>
<p>ss</p>

<h3 class="text-center" style="color: purple;">Admin Panel*</h3><hr>

<div class="container col-md-12 mb-3 p-3">
    <a class="btn btn-outline-info btn-md col-md-5" href="{% url 'categoryaddingview' %}">Create Category</a>
    <a class="btn btn-outline-primary btn-md col-md-5" href="{% url 'imageuploadview' %}">Upload Image</a>
    <a class="btn btn-outline-info btn-md col-md-5 mt-2" href="{% url 'categorydeleteview' %}">Delete Category</a>
    <a class="btn btn-outline-primary btn-md col-md-5 mt-2" href="{% url 'imagedeleteview' %}">Delete Image</a>
</div>

<p class="text-danger ml-5">* This for only admins, Users don't use this feature or this page ! !</p>
{% endblock photos %}

</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>UniQ</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
    <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.7.0/css/all.css' %}" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<!--
    
TemplateMo 556 Catalog-Z

https://templatemo.com/tm-556-catalog-z

-->
</head>
<body>
<!-- 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav> -->
      
    <nav class="navbar navbar-expand-lg shadow-sm p-2 mb-5 rounded" id="navbar">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <h2>Uniq Walls</h2>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-link-1" aria-current="page" href="{% url 'category' %}">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-3" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-4" href="{% url 'contact' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-2" href="{% url 'adminpage' %}">Admin Panel</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-" href="">Welcom {{user}}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-4" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-4" href="{% url 'accountsprofile' %}"><i class="fas fa-user-circle"></i></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-" href="{% url 'login' %}"><button type="button" class="btn btn-info rounded-pill text-light">Signin</button></a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    <div class="d-flex justify-content-center align-items-center" data-parallax="scroll"></div>

    {% block photos %}

    {% endblock %}
    
</body>

<style>
    #navbar {
        position: fixed;
        z-index: 0;
        background-color: rgb(255, 255, 255);
        width: 100%;
        z-index: 99;
    }
</style>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}
    <div>
        <p>Hidden</p>
        <p>Hidden</p>
    </div>

    <div class="row tm-mb-90 tm-gallery" id="img-div">
    {% for category in categories %}
        <h1 style="text-align: center; color: #009999;">{{ category.title }}</h1>
        {% for cat in category.image_set.all %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">
                <img src="{{ cat.image.url }}" alt="Image" class="img-fluid">
                <a href="{% get_media_prefix %}{{ img.image }}" download="{{ img.title }}.jpg">
                    <i style="float: right;" class="fas fa-download fa-lg mt-2"></i>
                </a>
                <span>{{ cat.view_count }} views</span><br>
                <span class="tm-text-gray-light">{{ cat.date }}</span>
                {% comment %} <div class="d-flex justify-content-between tm-text-gray">
                </div> {% endcomment %}
            </div>
        {% endfor %}
    {% endfor %}
    </div>

<style>
    #img-div {
        margin-top: 20px;
        padding: 10px;
    }
    .fa-download {
        color: rgba(1, 71, 112, 0.678);
    }
</style>
{% endblock photos %}

templates/category_adding.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}

<p>ss</p>
<p>ss</p>
    <div class="container col-md-5 border border-dark mb-4">
        <h3 class="text-primary">Create Category</h3>
        <form method="POST">
        {% csrf_token %}
            {{form}}
            <button class="btn btn-outline-warning btn-md btn-block mt-2 mb-2" type="submit">Submit</button>
        </form>
        <a href="{% url 'adminpage' %}"><button class="btn btn-outline-info btn-md btn-block mt-2 mb-2" type="submit">Cancle</button></a>
    </div>

{% endblock photos %}

templates/category_delete_view.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}
<p>ss</p>
<p>ss</p>

<div class="container">
    <div class="mb-5 table col-md-6">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Category</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                {% for cat in categories %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><h4>{{ cat.title }}</h4></td>
                    <td>
                        <a href="{% url 'categorydeletebutton' cat.pk %}">
                            <i class="fas fa-trash-alt fa-lg mt-2"></i>
                        </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
        </div>
</div>

{% endblock photos %}

templates/image_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}
<p>ss</p>
<p>ss</p>
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Do u want delete this image???</h2>
        <button class="btn btn-outline-info">Yaah</button>
    </form>
    <button class="btn btn-outline-primary">Nooop</button>
</div>
{% endblock photos %}

templates/image_delete_view.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}
<p>ss</p>
<p>ss</p>

<div class="row tm-mb-90 tm-gallery m-2" id="img-div">
    {% for img in images %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">
            <img src="{{ img.image.url }}" alt="Image" class="img-fluid">
            <a href="{% url 'imagedeletebutton' img.pk %}">
                <i style="float: right;" class="fas fa-trash-alt fa-lg mt-2"></i>
            </a>
            <span>{{ img.view_count }} views</span><br>
            <span class="tm-text-gray-light">{{ img.date }}</span>
            <!-- <div class="d-flex justify-content-betwee tm-text-gray">
            </div> -->
        </div>
    {% endfor %}
</div>
{% endblock photos %}

templates/image_upload.html
{% extends 'base.html' %}
{% load static %}
{% block photos %}

<p>ss</p>
<p>ss</p>
    <div class="container col-md-5 border border-dark mb-4">
        <h3 class="text-primary">Upload 4k Images</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-primary btn-md btn-block mt-2 mb-2" type="submit">Submit</button>
        </form>
        <a href="{% url 'adminpage' %}"><button class="btn btn-outline-warning btn-md btn-block mt-2 mb-2" type="submit">Cancle</button></a>
    </div>

{% endblock photos %}

</html>